const oquvchilar = [
    {
        id: 9342,
        password: 1234,
        name: "Dilmuhammad",
        surname: "Rustamov",
        coin: 545,
        group: "F2-1999",
        hp: 1550,
        teacher: "Sunatbek Krasavchik",
    }, {
        id: 9343,
        password: 1234,
        name: "Hondamir",
        surname: "Alimjanov",
        coin: 1022,
        group: "F2-1999",
        hp: 2505,
        teacher: "Sunatbek Krasavchik",
    },{
        id: 9346,
        password: 1234,
        name: "Azizbek ",
        surname: "Aliyev",
        coin: 1120,
        group: "F2-1999",
        hp: 2502,
        teacher: "Sunatbek Krasavchik",
    },{
        id: 9347,
        password: 1234,
        name: "Rustamov",
        surname: "Dilmuhammad",
        coin: 545,
        group: "F2-1999",
        hp: 1250,
        teacher: "Sunatbek Krasavchik",
    },{
        id: 9348,
        password: 1234,
        name: "Mahmudjon",
        surname: "Abbosov",
        coin: 542,
        group: "F2-1999",
        hp: 2250,
        teacher: "Sunatbek Krasavchik",
    },{
        id: 9348,
        password: 1234,
        name: "Fazilov",
        surname: "Kamron",
        coin: 522,
        group: "F2-1999",
        hp: 2220,
        teacher: "Sunatbek Krasavchik",
    },{
        id: 3348,
        password: 1264,
        name: "Tolaganov",
        surname: "Asadbek",
        coin: 522,
        group: "F2-1939",
        hp: 2220,
        teacher: "Sunatbek Krasavchik",
    },{
        id: 4348,
        password: 1234,
        name: "Fazilov",
        surname: "Kamron",
        coin: 522,
        group: "F2-1999",
        hp: 2220,
        teacher: "Sunatbek Krasavchik",
    },{
        id: 4348,
        password: 1234,
        name: "Fazilov",
        surname: "Kamron",
        coin: 522,
        group: "F2-1999",
        hp: 2220,
        teacher: "Sunatbek Krasavchik",
    },{
        id: 4348,
        password: 1234,
        name: "Fazilov",
        surname: "Kamron",
        coin: 522,
        group: "F2-1999",
        hp: 2220,
        teacher: "Sunatbek Krasavchik",
    }
]